select * from customer limit 20;

--Total revenue generated by male vs female customer
select gender,sum(purchase_amount) from customer
group by gender;

--which customers uses a discount but still spent more than the avg purchase amount
select customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount > (select avg(purchase_amount) from customer);

--which are the top 5 products with highest avg review rating
select item_purchased,round(avg(review_rating::numeric),2) from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--compare avg purchase amounts between standard and express shipping
select round(avg(purchase_amount),2),shipping_type from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--do subscribed customer spend more?compare to avg spend and total revenue
--betwen subcribers and non subscribers
select subscription_status,count(customer_id) as total_customers,
avg(purchase_amount) as avg_spend,sum(purchase_amount) as total_revenue from customer
group by subscription_status
order by avg_spend desc;

--which 5 products have the highest percentage of purchases with discounts applied
select item_purchased,
round(100*sum(case when discount_applied='Yes'then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--segment customers into new,returning and loyal based on their total
--number of previous purchases,and show the count of each segment
with customer_type as(
select customer_id,previous_purchases,
case
when previous_purchases =1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from customer
)
select customer_segment ,count(*) as "number_of_customers"
from customer_type
group by customer_segment;

--what are the top 3 most purchased products within each category
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count (customer_id) desc)as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;
);

--are customer who are repeat buyers also likely to subscribe (more than 5 purchases)
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status;

--what is the revenue contribution of each age group
select age_group,sum(purchase_amount)
from customer
group by age_group
order by sum(purchase_amount) desc